### ISSUE TITLE
flutter 2.8 support

### ISSUE THREAD

**Issue by laiiihz** [letsar/local_hero#7]
this package not working with the latest flutter version.

**Comment by laiiihz** [comment]
flutter sdk change this api `controller.link.leader` to `controller.link.debugLeader`, and does not work in other modes except debug.
[layer.dart#L2130](https://github.com/flutter/flutter/blob/cf4400006550b70f28e4b4af815151d1e74846c6/packages/flutter/lib/src/rendering/layer.dart#L2130)

**Comment by muhammadidrees** [comment]
Any update on this?

**Comment by cchamm** [comment]
Error encounter if building with flutter 2.8

`../flutter/.pub-cache/hosted/pub.dartlang.org/local_hero-0.2.0/lib/src/rendering/layer.dart:54:25: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
     - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../flutter/packages/flutter/lib/src/rendering/layer.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
        if (controller.link.leader == null) {
                            ^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/local_hero-0.2.0/lib/src/rendering/layer.dart:102:25: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
     - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../flutter/packages/flutter/lib/src/rendering/layer.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
        if (controller.link.leader == null) {
                            ^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/local_hero-0.2.0/lib/src/rendering/layer.dart:106:28: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
     - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../flutter/packages/flutter/lib/src/rendering/layer.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
        assert(controller.link.leader!.owner == owner,
                               ^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/local_hero-0.2.0/lib/src/rendering/layer.dart:117:44: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
     - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../flutter/packages/flutter/lib/src/rendering/layer.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
        ContainerLayer layer = controller.link.leader!;
                                               ^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/local_hero-0.2.0/lib/src/rendering/layer.dart:165:25: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
     - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../flutter/packages/flutter/lib/src/rendering/layer.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
        if (controller.link.leader == null) {
                            ^^^^^^`

**Comment by cchamm** [comment]
[This pull request](https://github.com/flutter/flutter/pull/92598) hide the `leader` field in the LayerLink class. I am requesting them to revert this change.

**Comment by kpk-i710** [comment]
> [This pull request](https://github.com/flutter/flutter/pull/92598) hide the `leader` field in the LayerLink class. I am requesting them to revert this change.

I really need this package, I don’t know how to fix it if I copy the package to my project for example from github. To work on the latest version of flutter?

**Comment by bimsina** [comment]
@kpk-i710 It's working in the master branch of flutter. You can switch to the master branch for now if that's possible.

**Comment by kpk-i710** [comment]
> @kpk-i710 It's working in the master branch of flutter. You can switch to the master branch for now if that's possible.

thanks for the information, while I'm better at the 2.5 stable version, it also works.

**Comment by mario202k** [comment]
I could suggest this : https://stackoverflow.com/questions/71468925/how-to-transform-a-widget-by-switching-view
But It's not a perfect solution. If someone wants to enhance my code... My best version is not there.

**Comment by Urvish24** [comment]
Do we have any update regarding this issue?

**Comment by laiiihz** [comment]
> Do we have any update regarding this issue?

flutter 3.0.x is working now 😆

**Comment by kpk-i710** [comment]
> > Do we have any update regarding this issue?
> 
> flutter 3.0.x is working now 😆

Seriously? Are there any warnings in the console?

**Comment by laiiihz** [comment]
@kpk-i710 yes its working(more detail:  flutter/flutter#92598) but have another warnings.
fix: https://github.com/flutter/website/blob/main/src/development/tools/sdk/release-notes/release-notes-3.0.0.md#if-you-see-warnings-about-bindings
